#include <stdlib.h>
#include <psxapi.h>
#include <psxgpu.h>
#include <psxgte.h>
#include <psxpad.h>
#include <psxspu.h>
#include <psxsio.h>
#include <psxcd.h>
#include <psxetc.h>
#include "BallTypes.h"
